version: '3'
services:
  app:
    container_name: node-service
    restart: always
    image: qwaded13/fec-service
    ports:
      - '80:3003'
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  mongo-seeder:
    container_name: mongo-seeder
    image: qwaded13/mongo-seeder
    depends_on:
      - mongo
    links: 
      - mongo